### ISSUE TITLE
changes in constructor/destructor semantics

### ISSUE THREAD

**Issue by starius** [akornatskyy/lua-libmemcached#3]
I propose the following changes to make memory and RAII things more clear:
- any `memcached` object accessible from Lua must be usable or closed
- close can't be called twice. Second attempt to call `close` should result in `lua_error`
  - add test
- if a call to memcached in `l_new` returns NULL, return lua_error("Can't create memcached object")
  - add test
- finalizer `__gc` and method `close` must be different C function. Although one can call another

**Comment by akornatskyy** [comment]
Second attempt to call `close` returns `false`, since it is not critical... end user can wrap call with `assert` to get an error.
